version: '2'

services:
  app:
    image: leisurehack/api:latest
    depends_on:
      - postgres
    env_file:
      - docker/env/app.env
      - docker/env/postgres.env

  postgres:
    env_file:
      - docker/env/postgres.env
    image: postgres:9.6

